### ISSUE TITLE
Not Saving or Being Recognized After Save and Restart Editor 

### ISSUE THREAD

**Issue by onebattleman** [shanecolb/sphinx-ue4#1]
Hello,

Awesome plugin and tutorial. It's super easy to use and works perfectly when you get it setup. But, I'm having a pretty frustrating issue. 

I'm trying to implement this into our project which is about we're about a year into it. So I can't simply start from scratch or use the creature you have in the example.  After setting everything up in my character Blueprint.  Following the tutorial and creating my phrases. I hit play and try everything out and it works! Which is awesome! 

Now, I'm going to close the project,  take a break and play some Battlefront. About an hour later I open the project back and I'm welcomed with  about 20 errors referring to Speech Recognition. I open up my character Blueprint and find out that all the nodes, everything referring to the Speech Recognition are in error. "Unknown Struct", "Invalid Nodes", and the Speech Recognition Variable has been reset to Object. 

I then open the Plugin's sample Blueprint and it's completely fine, all the nodes are there, nothing is invalid, it looks exactly like it's supposed to look. 

So, the issue is. The nodes and everything that has to do with the plugin seems to only save within the Sample Blueprint.

If I recreate all my code for the Plugin again for my character it works and the nodes stay the same for the session. I can hit "Save" and it saves without a problem, it's just opening the project that screws everything up again. Making it very difficult to work/move forward if I have to recreate the Speech Recognition code every time I reopen the project.

I'll do a video and share some screen shots. Is there something I'm missing? 

Here's a link to the Youtube Video: https://youtu.be/7nhErrtf1Q8

UE4 4.9.1
Blueprint Parent: Pawn

**Comment by onebattleman** [comment]
Before Closing Project: 
![2016-01-09_21h08_04](https://cloud.githubusercontent.com/assets/8759320/12219525/b2477a64-b715-11e5-9625-16ca2361a056.png)

![2016-01-09_21h08_12](https://cloud.githubusercontent.com/assets/8759320/12219526/b55c5ec2-b715-11e5-839a-3a30b0cd9a7e.png)

**Comment by onebattleman** [comment]
After Closing it and Reopening it: 
![2016-01-09_21h11_37](https://cloud.githubusercontent.com/assets/8759320/12219527/c837e3c2-b715-11e5-9736-104453a7e1b2.png)

![2016-01-09_21h11_43](https://cloud.githubusercontent.com/assets/8759320/12219528/cb30b0ae-b715-11e5-9394-6d10b94e87e6.png)

**Comment by onebattleman** [comment]
<iframe width="420" height="315" src="https://www.youtube.com/embed/7nhErrtf1Q8" frameborder="0" allowfullscreen></iframe>

**Comment by shanecolb** [comment]
Hi onebattleman,
Very strange, I hadn't seen this issue before.
Can you please create a super basic project demo, including a blueprint that suffers this issue.
Then if you can zip and send me a link to the project, and I will take a look.
I am glad you are liking it. It really is the early days for the plugin.
I hope that with more people using it, it will only get better over time.
Thanks,
Shane

**Comment by weilip** [comment]
Hi onebattleman,
I once encountered this problem. 
This is because of the loadingPhase in the speech recognition plugin.
In my case, I was able to solve it by adding the "LoadingPhase" : "PreDefault" in "SpeechRecognition.uplugin".
Not sure if this helps :)

Regards,
Weilip

![loadingphase](https://cloud.githubusercontent.com/assets/4279397/12219703/1dcad532-b78a-11e5-85dc-a6e9f40da540.JPG)

**Comment by shanecolb** [comment]
Thanks weilip,
onebattleman, let me know if this fixes the issue.
Regards,
Shane

**Comment by onebattleman** [comment]
Whoa! Thanks Man! That worked! Problem Solved! @weilip & @shanecolb
