### ISSUE TITLE
I have Level Loading issue Because of this Plugin! 

### ISSUE THREAD

**Issue by EleaSkipper** [shanecolb/sphinx-ue4#14]
Hi again ... I making a game using Blueprints and this C++ actor Plugin together to do some functions ... and it's going well when I test it in normal Play in Level editor and no problem with it but when I trying to export the game and Run it or Click **Launch** The level from UE4 editor the Level it's Not Loading and it keeps resetting and send me back to the same level ? and I'm sure the Problem Caused By Sphinx_ue4 
because it's not happened before ...

**Comment by shanecolb** [comment]
It could be literally anything, from that description..
You followed these instructions from the wiki? 

**NOTE: When packaging a project. Ensure the model folder is included in 'Additional non-asset directories to Copy' (in Project Settings=>Packaging.**

If you create a demo project (showcasing the issue) and send me a link, I can download and take a look.

**Comment by EleaSkipper** [comment]
when I export the Game Voice Capturing is nor working ?

**Comment by shanecolb** [comment]
*points to previous comment* 

> If you create a demo project (showcasing the issue) and send me a link, I can download and take a look.
