### ISSUE TITLE
About  Microphone Input

### ISSUE THREAD

**Issue by djego** [shanecolb/sphinx-ue4#2]
Hi, sorry for my english, I need to help me, I have your example TestSpeech project, but I can't be work correctly.

I put "I" and inmediatly apper  Message:  FAILURE

I think than my microphone should be configure with UE4 but I don't know like do these, or ¿Do you have another idea?

**Comment by onebattleman** [comment]
Please attach a screenshot to help us understand. 

What version of the engine are you using?

Does your microphone work outside of UE4? Such as Skype? If your microphone works with Skype then it's already setup to work with UE4.

**Comment by shanecolb** [comment]
Hi djego, what version of Unreal are you using? 
The most common cause for that error is when someone has create a "Content/models" folder instead of "Content/model". This causes the language model/dictionary etc to not be found.

**Comment by djego** [comment]
Thanks for response,

My version UE is 4.9

About the order, It's posible than mistake, i will try one more time, thank
you.

**Comment by djego** [comment]
Yes, it was the subject of directories
Now I have otrto problem, when I press the "I" key I get the message SUCCESS, but disables the microphone input, I close the game and come back to have microphone input. 
Any idea?

**Comment by shanecolb** [comment]
Sorry, I am not sure I follow.
What do you by disables microphone input? 
Are you trying to record audio at the same time as using the plugin?
Can you please explain in further detail.

**Comment by onebattleman** [comment]
Can you post a screenshot of the blueprint, that will help us rule out coding.

Try and build this in your player pawn and tell us if you get an error. 

![2016-01-18_19h32_50](https://cloud.githubusercontent.com/assets/8759320/12406387/6945c81e-be1a-11e5-9445-0bff84ac155f.png)

**Comment by djego** [comment]
OK, I explain you, my microphone work,  When I speech I hear myself, then I run my project (A simple project SpeechTest  than you shared in Google Docs)

When I put "I" Key (for initialize speech) I don't hear me, so I think than my microphone is disabled :/

When I Close my project, I hear me again.

I want to know if you or somebody had the same problem.

Note:  No try record 
Note2: I'll try with other microphone o headset

**Comment by djego** [comment]
Thank you Eric, I'll try with you screenshot.

**Comment by djego** [comment]
Hi, Eric, shanecolb 

I could to work correctly but I think there are delay in response =>  Print String 
It's correct ? or are there any reason for this delay?
Thank you so much for their support.

**Comment by onebattleman** [comment]
There is a small delay, (like all speech recognitions) it has to sort through/parse your speech into individual words then match them to its database and then check to see if it's a phrase in the word array that triggers the bound event. 

Basically, there's nothing you can do about the small delay. There's always going to be a delay but how long the delay is depends on the speed of the users computer.

Good to hear you go it working.
