### ISSUE TITLE
Pre-built plugin for Windows / Android for UE 4.11 ?

### ISSUE THREAD

**Issue by motorsep** [shanecolb/sphinx-ue4#6]
This is super awesome plugin!!!

Could you please provide a pre-built version for Windows / Android for UE4 4.11 ?

**Comment by shanecolb** [comment]
Thanks, the github repo includes binaries compiled for Windows.
Please follow the instructions in the following Wiki to get this to work on Windows.

https://wiki.unrealengine.com/Speech_Recognition_Plugin

Best bet is to download the example project, and examine the blueprint of the Character.

At the moment, this only works for Windows.
An Android port will be available in the coming weeks.

**Comment by motorsep** [comment]
Oh, ok. Thanks.

Really looking forward Android version !!!

**Comment by mrG7** [comment]
#woot !!

**Comment by pekayatt** [comment]
Would love to have this for Android, is this possible? Do you need help?

**Comment by shanecolb** [comment]
Sorry, since this time, I have been contacted by a company, and working on it exclusively as part of my work with them. Sorry about that. Once the project is finished, the plugin will be released...but unfortunately, it won't be any time soon.

**Comment by pekayatt** [comment]
Understood, but are you working on this project as your work now? 
From what I can understand it will be a paid plugin now, or it will remain open source?

Thanks,

**Comment by shanecolb** [comment]
The project will use the android port, once the project is released (at a later date), the plugin and the code will be too. Can't say too much more, other than that.
